#include <iostream>
using namespace std;
void GE7w2()
{system("cls"); cout<<"\033[33m" << "path/lms/GE5/lessons/W2" <<"\033[0m" << "\n" <<endl;

cout<<"History of Science and Technology in the Philippines"

"\n\nOne of the generally recognized imperatives of socioeconomic progress in the contemporary world is the need to develop the science and technology of a country. Especially since the post-World War II years, this has become the governments’ widespread concern. The problem of dependence on science and technology is one important dimension of this concern among Third World countries. This is because this is closely tied up with the integrity of their economic self-reliance and political sovereignty. A continuing imbalance between technological and scientific development among contemporary states exists with 98% of all development and research facilities located in developed countries and almost concerned wholly with the latter's problems. In United Nations-sponsored conferences, one salient issue is the autonomy or dependence in technology and science (Caoili, 2017)."

"\n\nReliable written information about the Philippine’s culture, technology, and society before the Spaniards’ arrival in 1521 is very little. According to sources, long before the arrival of the Spaniards, there were already numerous, scattered, thriving, relatively self-sufficient, and autonomous communities in the country. A generally simple level of technological development has been attained by early Filipinos as compared to the Japanese and Chinese. However, at that period of time, this knowledge was sufficient enough for their needs."

"The early Filipinos gradually learned to make metal tools and implements of copper, gold, bronze and, later, iron. Practically, these were the same commodities of trade between China and the islands. When the Spanish colonial officials arrived in the Philippines more than two centuries later, they recorded this trade."


"\n\nAlthough no temples or worship places were found by the Spaniards, pre-colonial Filipino were still highly superstitious. The Filipinos, using their own system, knew how to read and write, but it was mainly used for letters and messages. They did not seem to have developed a written literary tradition at that time. Oral literature was instead used to pass on cultural knowledge. Still, a system of writing would have led to a more systematic accumulation and dissemination of knowledge, a condition that is necessary for the development of science and technology. "

"\n\nThroughout the Spanish regime, University of Santo Tomas remained as the highest institution of learning. Initially, the university granted degrees in humanities, theology, and philosophy. The faculty of jurisprudence and canonical law was then established in the 18th century. Afterwards, the schools of pharmacy and medicine were opened in 1871. A preparatory course with subjects in general chemistry and natural history are consisted in the study of pharmacy. 5 years of studies in subjects like pharmaceutical operations at the school of pharmacy are also included in the study of pharmacy."

"\n\nA German physician of Manila at the start of the American regime submitted a report on UST’s medical college conditions to the authorities. UST’s lack of library facilities and the use of outdated equipment was mentioned in the report, among others. Moreover, the Suez Canal’s opening in 1869 brought about a consequent ease in communication and travel. This also allowed the scientific knowledge and liberal ideas of the West to reach the Philippines. As a result of the increase in commerce between the Philippines and the rest of the world, prosperity enabled Filipino students to go to Europe for professional advanced studies."

"\n\nReligious orders had established several charity hospitals in the archipelago and provided the bulk of this public service towards the end of the 16th century. During the first 2 centuries of the Spanish rule, development in Philippine agriculture and industry was very little. This was mostly due to the dependence of the Spanish colonizers on the profits from the Galleon or Manila-Acapulco trade."

"\n\nOn the other hand, it was the Jesuits, who founded the Manila Observatory in 1865, that promoted meteorological studies. The Observatory was then made into a central station of the Philippine Weather Bureau in 1901. This was set up by the American colonial authorities. It remained under the Jesuit scientists and provided not just meteorological studies, but also astronomical and seismological studies."

"\n\nWhen it comes to the time of the short-lived Philippine Republic (1898-1900), development in science and technology was very little. To establish a secular educational system, the government took steps by a decree of 19 October 1898. This created the Universidad Liter aria de Filipinas as a secular, state-supported institution of higher learning. "

"\n\nDuring the American regime, science and technology in the country rapidly advanced. The simultaneous government support and encouragement for an extensive public education system; the scholarship granting in science and engineering for higher education; the establishment of science-based public services and the organization of science research agencies made the rapid advancements possible."

"\n\nThe short-run needs for professionally trained Filipinos in the colonial government's programs and organization were satisfied with the establishment of the University of the Philippines. The university remained to be the only higher education institution for that is publicly supported. However, since the increasing social demand for universities could not be met, it was left to the enterprising Filipino’s initiative. And for a lot of Filipinos, it is private education that has become the alternative for professional education."

"\n\nConcurrent appointments were held by the staff members of the Bureau of Government Laboratories as faculty members of the University of the Philippine’s College of Medicine and other units, and as well as appointments at the Philippine General Hospital. Likewise, officers of the Bureau of Health were appointed to the College of Medicine faculty. These scientists all conducted their research work at the Bureau of Science."

"\n\nIn 1935, the Philippine Commonwealth was inaugurated which was by this time completely under Filipino management, continued to expand its public school system to accommodate the increasing number of schoolchildren. There was a significant increase in trained scientists and engineers in the Philippines before the Second World War."

"\n\nIn 1982, NSDB was further reorganized into a National Science and Technology Authority (NSTA) composed of four research and Development Councils; Philippine Council for Agriculture and Resources Research and Development; Philippine Council for Industry and Energy Research Development; Philippine Council for Health Research and Development and the NRCP. The expanding number of science agencies gave rise to a demand for high caliber scientists and engineers to undertake research and staff universities and colleges. Hence, measures were taken towards the improvement of the country’s science and human resources. "

"\n\nThe Philippine Commonwealth was inaugurated and ushered into a period of transition to political independence in 1935. The importance of promoting scientific development for the economic development was acknowledged by the Constitution, which was by this time, completely under Filipino management. Higher education was mainly provided by the private sector on the whole. This led to the combined significant increase in trained scientists and engineers in the Philippines before the Second World War."

"\n\nThe Philippine economy’s continuing dependence on the United States even after independence in 1946, as a result of the free trade relations and the virtual imposition of the \"parity\" amendment to the Philippine Constitution by the US Congress, has perpetuated the predominantly agricultural and rural character of Philippine economy and society. This dependent development of Philippine society and economy has had serious repercussions for the advancement of Philippine science and technology. Increasing social demand for higher education has led to the growth of highly trained professional human resources, particularly scientists, engineers and physicians. However, because of the underdeveloped state of the economy, many of these science-based professionals have been unemployed or underemployed. Consequently, many of them have been forced to migrate to developed countries, thus creating a \"brain drain\" or loss of valuable human resources for the Philippines. There is thus a need for the government to critically re-examine the interrelations between past and present education and science policies with those of its economic development policies in order to be able to redirect these towards the goal of attaining a strong, self-reliant economy and society. A well-developed national science and technology is a critical factor in the achievement of this goal (Caoili, 2017)."


"\n\n\nScience in Transition"

"\n\nIn the past, scientific methods and institutions tended to emphasize the study of individual natural processes rather than systems, analysis more than synthesis, and understanding nature more than predicting its behavior. And in many instances, science focused on short-term, small-scale problems, often in monodisciplinary mode, rather than on long-term, large-scale or integrated problems. While these perspectives and approaches have built up a considerable base of knowledge and led to a vast portfolio of useful technologies, especially in the 20th century, many of the problems now facing humankind can be solved through a holistic approach."

"\n\nThe impact on individual people, communities, and the environment of technological interventions are carefully considered. Science became more multidisciplinary and its practitioners continued to promote cooperation and integration between the social and natural sciences. A holistic approach demanded that science drew on the contributions of the humanities (such as history and philosophy), local knowledge systems, aboriginal wisdom, and the wide variety of cultural values."


"\n\nThe influence of science on people’s lives is growing. While in the history of the human species, recent benefits to humanity are unparalleled, the impact has been harmful or the long-term effects give causes for serious concerns in some instances. Exists today is a considerable measure of fear of technology and public mistrust of science. This partly stems from the belief by some individuals and communities that they will be the ones to suffer the indirect negative consequences of technical innovations which was introduced to benefit only a privileged minority. A duty on scientists to proceed with great caution both in what they do and what they say is placed on them due to the power of science. Scientists reflect on the social consequences of the technological applications or dissemination of partial information of their work and explain to the public and policy makers alike the degree of scientific uncertainty or incompleteness in their findings. At the same time, though, they should not hesitate to fully exploit the predictive power of science, duly qualified, to help people cope with environmental change, especially in cases of direct threats like natural disasters or water shortages."

"\n\nThe current trend toward privatization in many countries is influencing the focus and practice of science. In some instances, increasing research capacity and knowledge in selected areas is the net result. However, there is still major concern that the trend may be undermining public-sector science, especially fundamental research and efforts to solve socially important problems that pose no interest to commercial enterprises. For example, the job of public research is more difficult because of patent protection of private intellectual property. There is also concern over the social implications of private ownership and control of technology, and its effect on broad public scientific literacy, and on options for public choice."

"\n\nAnother major trend shaping science is globalization. The end of the Cold War, growing technology demand from emerging economies, world recognition of the interconnectedness of the planet’s biophysical systems and improved communications, especially via the Internet - all these forces are boosting cross-border scientific cooperation and information exchange between individual researchers, institutions and governments. However, only in a handful of scientifically advanced countries are much of the expansion occurring in. More effort is needed to ensure that all countries, rich and poor, and a wide range of world cultures are included in technology transfer and collaborative research for science to be truly global. This is especially important in areas like global climate change which will affect, sooner or later, all human beings. With the right policies in place, joint scientific work in critical areas like the Arctic, for example, can serve as a model for other global cooperation types."


"\n\n\nScience Policy and Ethics "

"\n\nIn themselves, scientific advances are never a guarantee of social benefit. Technology must not be treated as a master, rather as a servant of society. Increasing commercial productivity, while at the same time necessary, unemployment and poverty is not a socially acceptable solution. Science must be fully integrated with broad societal needs, but this tenet is not yet fully accepted. One reason for public mistrust of science is that ordinary people feel they will sometimes end up being the ones to suffer the costs of technological innovation. It was suggested repeatedly at the North American meeting that the time has come to introduce an international code of ethical conduct for scientists to ensure that science is directed for the public good."

"\n\nIn their daily work, scientists are sometimes isolated from the mainstream society, which makes it difficult for them to be clearly aware of public needs. Conversely, when policy makers are in need of sometimes urgent advice on technical matters, they may be unaware of the scientific expertise residing under their very noses. Through the proactive involvement of scientists in policy making, society has so much to gain."

"\n\nMedical biotechnology is a leading-edge area of science in which the pace of progress is perhaps faster than society’s capacity to deal with the ethical and social implications. Genetic research, while offering major benefits for disease diagnosis and treatment, also poses serious questions about the nature and sanctity of human life and the protection of human rights. The possibility that genetic technology could be commandeered by powerful groups to pursue goals in their own interests, but which may be socially destructive or discriminatory is not to be considered lightly. To disabled persons, it is an issue of particular importance. Greater dialogue between scientists, policy makers and the public, especially those groups disproportionately affected by technological developments, is clearly needed."

"\n\nOne major concern is that recent advances in health sciences will lead to the \"genetification of medicine.\" This is a trend toward understanding and explaining human beings and human health largely in terms of genes and their interactions. The role of social and environmental factors increasingly receiving insufficient attention, leading to a one-dimensional view of diseases and disabilities is a worry with this."

"\n\nThe \"commodification\" of basic human needs such as food, shelter, clothing, fuel, and health services is a further ethical issue in science. Often family-based, many of these items have traditionally been supplied through non-monetary social support structures in many countries. As cash economies and government welfare programs increasingly treat these necessities of life simply as commodities to be bought and sold, there is a serious risk that technological innovations, stimulated by scientists working within a commercial framework, will be exploited mainly by well-to-do minorities, with little or no benefit to the poor. More attention is needed to the potential of science to improve human social conditions in non-material ways.\n\n"<<endl;
	getchar(); getchar();
}